export enum VerificationType {
  PHYSICAL_MECHANICAL = 'PHYSICAL_MECHANICAL',
  EMISSIONS = 'EMISSIONS',
}

export enum VerificationResultStatus {
  PASSED = 'PASSED',
  FAILED = 'FAILED',
  CONDITIONAL = 'CONDITIONAL',
  CANCELLED = 'CANCELLED',
}

export enum VerificationObligationStatus {
  PENDING = 'PENDING',
  OWNER_CONFIRMED = 'OWNER_CONFIRMED',
  OWNER_DECLINED = 'OWNER_DECLINED',
  REQUESTED_ASSISTANCE = 'REQUESTED_ASSISTANCE',
  SCHEDULED = 'SCHEDULED',
  COMPLETED = 'COMPLETED',
  OVERDUE = 'OVERDUE',
  CANCELLED = 'CANCELLED',
}

export enum VerificationOwnerResponse {
  CONFIRMED = 'CONFIRMED',
  DECLINED = 'DECLINED',
  REQUEST_ASSISTANCE = 'REQUEST_ASSISTANCE',
  REQUEST_RESCHEDULE = 'REQUEST_RESCHEDULE',
}

export enum VerificationObligationHistoryAction {
  CREATED = 'CREATED',
  OWNER_RESPONSE = 'OWNER_RESPONSE',
  ADMIN_UPDATED = 'ADMIN_UPDATED',
  SCHEDULED = 'SCHEDULED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  SYSTEM_UPDATED = 'SYSTEM_UPDATED',
}
